substitutions:
  _REGION: asia-northeast3
  _SERVICE: etf-pullback-alert

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/etf-alert/${_SERVICE}:$SHORT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/etf-alert/${_SERVICE}:$SHORT_SHA
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/etf-alert/${_SERVICE}:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --memory=512Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=1

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/etf-alert/${_SERVICE}:$SHORT_SHA
